
server:
  port: 2004
spring:
  application:
    name: purchaseRibbon
  devtools:
    restart:
      enabled: true
PAYMENTSERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.com:8081/eureka/,http://eureka-server2.com:8082/eureka/
    fetch-registry: true
    register-with-eureka: true
