server:
  port: 2006
spring:
  application:
    name: purchaseHystrixService
  devtools:
    restart:
      enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.com:8081/eureka/,http://eureka-server2.com:8082/eureka/
    fetch-registry: true
    register-with-eureka: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.pyh.purchase_openfeign.service.OpenFeignService: info
feign:
  hystrix:
    enabled: true