server:
  port: 8082

eureka:
  instance:
    hostname: eureka-server2.com

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: #注意这里的defaultZone的写法，写成default-zone是不对的
      defaultZone: http://eureka-server.com:8081/eureka/
  server:
    peer-node-read-timeout-ms: 6000
spring:
  devtools:
    restart:
      enabled: true
